replicaCount: 1

image:
  repository: your-docker-registry/faceit
  pullPolicy: IfNotPresent
  tag: "latest"

faceitApiKey: ""
djangoSecretKey: ""

debug: "false"
allowedHosts:
  - "localhost"

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

database:
  host: ""
  port: 5432
  name: ""
  user: ""
  password: ""


ingress:
  enabled: false
  hosts:
    - host: faceit.example.com
      paths:
        - "/"
  tls: []
