apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "faceit.fullname" . }}
  labels:
    {{- include "faceit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "faceit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "faceit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: faceit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: faceit-config
          env:
            - name: FACEIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: faceit_api_key
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: django_secret_key
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: db_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: db_port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: db_name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faceit-credentials
                  key: db_password
          ports:
            - containerPort: {{ .Values.service.port }}
