apiVersion: v1
kind: Secret
metadata:
  name: faceit-credentials
type: Opaque
data:
  faceit_api_key: {{ .Values.faceitApiKey | b64enc }}
  django_secret_key: {{ .Values.djangoSecretKey | b64enc }}
  db_host: {{ .Values.database.host | b64enc }}
  db_port: {{ printf "%d" .Values.database.port | b64enc }}
  db_name: {{ .Values.database.name | b64enc }}
  db_user: {{ .Values.database.user | b64enc }}
  db_password: {{ .Values.database.password | b64enc }}

