apiVersion: v1
kind: Service
metadata:
  name: {{ include "faceit.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "faceit.selectorLabels" . | nindent 4 }}
