apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faceit-postgres
  namespace: faceit
spec:
  serviceName: faceit-postgres
  replicas: 1
  selector:
    matchLabels:
      app: faceit-postgres
  template:
    metadata:
      labels:
        app: faceit-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: faceit_db
            - name: POSTGRES_USER
              value: faceit
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faceit-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 10Gi
